---
name: test-and-push

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      
      - name: prepare
        id: prepare
        run: |
          DOCKER_IMAGE=${{ secrets.DOCKER_USERNAME }}/prometheus-awair-exporter
          DOCKER_PLATFORMS=linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          TAGS="--tag ${DOCKER_IMAGE}:latest"
          TAGS="$TAGS --tag ${DOCKER_IMAGE}:$(git rev-parse --short HEAD)"
          GIT_TAG=$(git tag --points-at HEAD | tr -d '\n')
          if [ ! -z "$GIT_TAG" ]; then TAGS="$TAGS --tag ${DOCKER_IMAGE}:${GIT_TAG}"; fi
          echo DOCKER_IMAGE=${DOCKER_IMAGE} >> $GITHUB_ENV
          echo BUILDX_ARGS="--platform ${DOCKER_PLATFORMS} ${TAGS} --file ./Dockerfile ./" >> $GITHUB_ENV

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker Buildx (build)
        if: success () && github.event_name == 'pull_request'
        run: |
          docker buildx build --output "type=image,push=false" ${{ env.BUILDX_ARGS }}

      - name: Docker Login
        if: success() && github.event_name == 'push'
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin

      - name: Docker Buildx (push)
        if: success() && github.event_name == 'push'
        run: |
          docker buildx build --output "type=image,push=true" ${{ env.BUILDX_ARGS }}

      - name: Clear
        if: always() && github.event_name == 'push'
        run: |
          rm -f ${HOME}/.docker/config.json

  
  